---
# A custom task is created using a Jinja2 template based on the
#  appliance_deployment_scheme and the appliance_networking_mode
# If a PSC and vCSA are to be deployed we need to run this task twice
- name: Create custom task to deploy the appliances
  template: src="{{ the_one_task_template }}" dest="{{ the_one_task }}"
  tags: create_new_task_the_one
