#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
# - name: ---> OVFTOOL LOG FILE LOCATION <----
#   tags: debug
#   debug: msg="The ovftool log file is {{ chaperone_log_dir }}/{{ appliance_deployment_scheme }}_{{ appliance_networking_mode }}.log"

- name: Set the FQDN fact when deploying IB PSC
  set_fact:
      ib_psc_fqdn: "{{ ib_psc_appliance_name }}.{{ dns_domain_name }}"
  tags:
    - create_ib_psc_task

- name: Set the FQDN fact when deploying OOB PSC
  set_fact:
      oob_psc_fqdn: "{{ oob_psc_appliance_name }}.{{ dns_domain_name }}"
  tags:
    - create_oob_psc_task

- name: Set the FQDN fact when deploying IB vCenter
  set_fact:
      ib_vcenter_fqdn: "{{ ib_vcenter_appliance_name }}.{{ dns_domain_name }}"
  tags:
    - create_ib_vcenter_task
    - create_ib_vcenterpsc_task

- name: Set the FQDN fact when deploying OOB vCenter
  set_fact:
      oob_vcenter_fqdn: "{{ oob_vcenter_appliance_name }}.{{ dns_domain_name }}"
  tags:
    - create_oob_vcenter_task
    - create_oob_vcenterpsc_task

- name: Create a task from template to deploy an IB PSC
  template: src=ib_psc_ovf_deploy.yml.j2 dest={{ vcsa_task_directory }}/deploy_app.yml
  tags:
    - create_ib_psc_task

- name: Create a task from template to deploy an OOB PSC
  template: src=oob_psc_ovf_deploy.yml.j2 dest={{ vcsa_task_directory }}/deploy_app.yml
  tags:
    - create_oob_psc_task

- name: Create a task from template to deploy an IB vCenter
  template: src=ib_vcenter_ovf_deploy.yml.j2 dest={{ vcsa_task_directory }}/deploy_app.yml
  tags:
    - create_ib_vcenter_task

- name: Create a task from template to deploy an OOB vCenter
  template: src=oob_vcenter_ovf_deploy.yml.j2 dest={{ vcsa_task_directory }}/deploy_app.yml
  tags:
    - create_oob_vcenter_task

- name: Create a task from template to deploy an OOB vCenter with embedded PSC
  template: src=oob_vcenterpsc_ovf_deploy.yml.j2 dest={{ vcsa_task_directory }}/deploy_app.yml
  tags:
    - create_oob_vcenterpsc_task

- name: Create a task from template to deploy an IB vCenter with embedded PSC
  template: src=ib_vcenterpsc_ovf_deploy.yml.j2 dest={{ vcsa_task_directory }}/deploy_app.yml
  tags:
    - create_ib_vcenterpsc_task

- name: Deploy the appliance
  include: deploy_app.yml
  tags:
    - deploy_vcenter_psc_ova

# The failed_when statement above should catch both soft failures (Monitor failed) and hard
#  failures (return code > 1). If a failure occurs we need to cleanup the VM that is deployed
- name: Destroying the appliance
  ignore_errors: True
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    guest: "{{ appliance_vcenter_name }}"
    state: absent
    force: yes
  tags:
    - cleanup_combined
    - cleanup_psc
    - cleanup_vcsa

# Unmount the ISO
- name: Unmount ISO
  mount: src="{{ chaperone_vcsa_iso }}" name="{{ mount_dir_path }}" fstype=iso9660 state=unmounted
  become: True
  tags:
    - cleanup

# Now that the ISO is unmounted we grab the existing metadata for the mount directory. Crude
# and needs to built with something more intelligence.
- name: Retrieve info about the mount directory
  stat: path="{{ mount_dir_path }}"
  register: mount_dir_stat_unmounted
  tags:
    - cleanup

# Destroy the mount directory
- name: Destroy the temp mount directory
  file: path="{{ mount_dir_path }}" state=absent
  when: mount_dir_stat_unmounted.stat.wusr == True
  become: True
  tags:
    - cleanup
