---
# Using the does_vm_exist custom module verify that the dedicated PSC appliance
# name in vCenter
- name: Verify if the dedicated PSC appliance name already exists in vCenter
  does_vm_exist:
    vcenter_host: "{{ vcenter_host }}"
    vcenter_user: "{{ vcenter_user }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_port: "{{ vcenter_port }}"
    vm_name: "{{ psc_appliance_vcenter_name }}"
  when: appliance_deployment_scheme == "Dedicated PSC"
  register: psc_appliance_exists_combined

# Using the does_vm_exist custom module verify that the dedicated vCSA appliance
# name in vCenter
- name: Verify if the dedicated vCSA appliance already exists in vCenter
  does_vm_exist:
    vcenter_host: "{{ vcenter_host }}"
    vcenter_user: "{{ vcenter_user }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_port: "{{ vcenter_port }}"
    vm_name: "{{ vcsa_appliance_vcenter_name }}"
  when: appliance_deployment_scheme == "Embedded PSC"
  register: vcsa_appliance_exists_combined
