---
# Using the ovftool binary, deploys the required appliance(s)
# The failed_when property is used to capture both soft failures ("Monitor failed:") and hard
#  failures (return code > 0)
- name: Deploy the {{ appliance_deployment_scheme }} appliance using {{ appliance_networking_mode }} IP addressing
  command: >
    {{ ovftool }}
    --sourceType=OVA
    --acceptAllEulas
    --allowExtraConfig
    --noSSLVerify
    --diskMode=thin
    --skipManifestCheck
    --X:injectOvfEnv
    --powerOn
    --X:httpTimeout='{{ ovftool_http_timeout }}'
    --X:enableHiddenProperties
    --X:connectionFileTransferRetryCount=3
    "--X:monitorInstallFiles=file://{{ esx_username }}:{{ '{{ esx_password }}' }}@/var/log/firstboot/rpmInstall.json, file://{{ esx_username }}:{{ '{{ esx_password }}' }}@/var/log/firstboot/fbInstall.json"
    '--X:monitorOutputFile=/tmp/vcsa-cli-installer-progress-{{ 10000000 |random}}.json'
    '--X:logFile={{ chaperone_log_dir }}/{{ appliance_deployment_scheme }}_{{ appliance_networking_mode }}.log'
    --X:logLevel=verbose
    --X:logTransferHeaderData
    --X:waitForIp
    --prop:guestinfo.cis.appliance.root.shell=/bin/bash
    --prop:guestinfo.cis.db.type=embedded
    --diskMode=thin
    --datastore={{ '{{ esx_datastore }}' }}
    "--network={{ '{{ esx_network }}' }}"
    "--prop:guestinfo.cis.vmdir.password={{ '{{ sso_password }}' }}"
    --prop:guestinfo.cis.vmdir.site-name='{{ sso_site_name }}'
    --prop:guestinfo.cis.vmdir.domain-name='{{ sso_domain_name }}'
    --prop:guestinfo.cis.appliance.ssh.enabled='{{ ssh_enable }}'
    --prop:guestinfo.cis.appliance.time.tools-sync='{{ time_tools_sync }}'
    --prop:guestinfo.cis.appliance.net.addr.family='{{ ip_family }}'
    --name='{{ psc_appliance_vcenter_name }}'
    --prop:guestinfo.cis.appliance.root.passwd={{ '{{ psc_appliance_root_password }}' }}
    --deploymentOption=infrastructure
    --prop:guestinfo.cis.vmdir.first-instance=true
    --prop:guestinfo.cis.appliance.net.mode=dhcp
    '{{ mount_dir_path }}/{{ vcsa_ova }}'
    "vi://{{ esx_username | urlencode }}:{{ '{{ esx_password | urlencode }}' }}@{{ esx_hostname }}"
  register: deploy_ovf_cmd_result
  ignore_errors: True
  failed_when: "'Monitor failed:' in deploy_ovf_cmd_result.stdout or deploy_ovf_cmd_result.rc > 0"
